### ISSUE TITLE
Builds aren't working for node-mapnik@4.0.0-dev

### ISSUE THREAD

**Issue by mapsam** [mapnik/documentation#12]
Noticed the mapnik.org documentation is still at 3.6, where it should be at 3.7 and 4.0 now that master is on `4.0.0-dev`. The following error is coming from travis:

```
Building 4.0 from mapnik version 4.0.0-dev
/home/travis/build/mapnik/documentation/node_modules/documentation/lib/commands/build.js:60
      throw err;
      ^
TypeError: Cannot read property 'match' of undefined
    at isJSDocComment (/home/travis/build/mapnik/documentation/node_modules/documentation/lib/is_jsdoc_comment.js:16:32)
    at Array.filter (native)
    at parsePolyglot (/home/travis/build/mapnik/documentation/node_modules/documentation/lib/parsers/polyglot.js:17:6)
    at /home/travis/build/mapnik/documentation/node_modules/documentation/index.js:107:36
    at Array.reduce (native)
    at /home/travis/build/mapnik/documentation/node_modules/documentation/index.js:106:16
    at module.exports (/home/travis/build/mapnik/documentation/node_modules/documentation/lib/input/shallow.js:23:10)
    at expandInputs (/home/travis/build/mapnik/documentation/node_modules/documentation/index.js:53:3)
    at module.exports (/home/travis/build/mapnik/documentation/node_modules/documentation/index.js:96:10)
    at Object.build (/home/travis/build/mapnik/documentation/node_modules/documentation/lib/commands/build.js:82:3)
```

I suspect this is from an outdated version of documentation.js. Will require some debugging, but the docs are looking fine at mapnik.org for now.

cc @springmeyer @artemp @GretaCB

**Comment by springmeyer** [comment]
thanks for noticing and ticketing @mapsam
